---
  kind: pipeline
  type: docker
  name: terraform
  
  platform:
    arch: amd64
    os: linux

  steps:
    - name: test
      image: alpine
      commands:
        - date
      when:
        branch:
          - master
        event:
          - push
