version: "3"
services: 
  selenium:
    image: selenium/standalone-chrome-debug
    container_name: selenium-chrome
    hostname: selenium-chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - developer

networks:
  developer:
  